export const USER_ENTRY_REQUEST="USER_ENTRY_REQUEST";
export const USER_ENTRY_SUCCESS="USER_ENTRY_SUCCESS";
export const USER_ENTRY_FAIL="USER_ENTRY_FAIL";

export const USER_UPDATE_REQUEST="USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS="USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL="USER_UPDATE_FAIL";

export const USER_DELETE_REQUEST="USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS="USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL="USER_DELETE_FAIL";

export const USERLIST_GET_REQUEST="USERLIST_GET_REQUEST";
export const USERLIST_GET_SUCCESS="USERLIST_GET_SUCCESS";
export const USERLIST_GET_FAIL="USERLIST_GET_FAIL";
